"""empty message

Revision ID: 69ceaeddbdc9
Revises: 
Create Date: 2023-07-27 19:04:43.560267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ceaeddbdc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Foody_admins',
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Password', sa.String(length=102), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=11), nullable=False),
    sa.Column('TryNumber', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.Column('LastLoginDate', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Password'),
    sa.UniqueConstraint('PhoneNumber'),
    sa.UniqueConstraint('PublicKey'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('Foody_days',
    sa.Column('NameFa', sa.String(length=64), nullable=False),
    sa.Column('NameEn', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('NameEn'),
    sa.UniqueConstraint('NameFa'),
    sa.UniqueConstraint('PublicKey')
    )
    op.create_table('Foody_foods',
    sa.Column('Images', sa.JSON(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey')
    )
    op.create_table('Foody_sections',
    sa.Column('Name', sa.String(length=64), nullable=False),
    sa.Column('Description', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name'),
    sa.UniqueConstraint('PublicKey')
    )
    op.create_table('Foody_food_days',
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['Foody_days.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['Foody_foods.id'], )
    )
    op.create_table('Foody_log_admins',
    sa.Column('AdminID', sa.Integer(), nullable=True),
    sa.Column('Action', sa.String(length=512), nullable=False),
    sa.Column('IpAddress', sa.String(length=15), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['AdminID'], ['Foody_admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey')
    )
    op.create_table('Foody_users',
    sa.Column('Username', sa.String(length=64), nullable=False),
    sa.Column('Password', sa.String(length=102), nullable=False),
    sa.Column('FirstName', sa.String(length=256), nullable=False),
    sa.Column('LastName', sa.String(length=265), nullable=False),
    sa.Column('NationalCode', sa.String(length=11), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=11), nullable=False),
    sa.Column('SectionID', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.Column('EmployeeCode', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['SectionID'], ['Foody_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('EmployeeCode'),
    sa.UniqueConstraint('NationalCode'),
    sa.UniqueConstraint('PhoneNumber'),
    sa.UniqueConstraint('PublicKey'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('Foody_orders',
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('FoodID', sa.Integer(), nullable=True),
    sa.Column('DayID', sa.Integer(), nullable=True),
    sa.Column('OrderDate', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['DayID'], ['Foody_days.id'], ),
    sa.ForeignKeyConstraint(['FoodID'], ['Foody_foods.id'], ),
    sa.ForeignKeyConstraint(['UserID'], ['Foody_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Foody_orders')
    op.drop_table('Foody_users')
    op.drop_table('Foody_log_admins')
    op.drop_table('Foody_food_days')
    op.drop_table('Foody_sections')
    op.drop_table('Foody_foods')
    op.drop_table('Foody_days')
    op.drop_table('Foody_admins')
    # ### end Alembic commands ###
